# Generated by Django 6.0.3 on 2026-04-02 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the site', max_length=255, unique=True)),
                ('code', models.CharField(help_text='Short identifier used in logs and displays, e.g. NBI-01', max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, help_text='City, county, or region', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sites', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, help_text="Users who can view and manage this site's projects", related_name='sites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'db_table': 'projects_site',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Descriptive name, e.g. 'Nairobi — Enrollment Form'", max_length=255)),
                ('description', models.TextField(blank=True)),
                ('redcap_url', models.URLField(help_text='Full REDCap API URL for this project, e.g. https://redcap.site.ac.ke/api/', max_length=500)),
                ('project_id', models.PositiveIntegerField(blank=True, help_text='REDCap internal project ID — fetched automatically on token validation', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('testing', 'Testing')], default='active', max_length=20)),
                ('sync_forms', models.TextField(blank=True, help_text='Comma-separated REDCap form names to include in sync. Leave blank for all forms.')),
                ('sync_fields', models.TextField(blank=True, help_text='Comma-separated field names to include in sync. Leave blank for all fields.')),
                ('record_id_prefix', models.CharField(blank=True, help_text="Optional prefix added to record IDs before pushing to registry, e.g. 'NBI-'", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(help_text='The site this project belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.site')),
            ],
            options={
                'verbose_name': 'Site Project',
                'verbose_name_plural': 'Site Projects',
                'db_table': 'projects_site_project',
                'ordering': ['site__name', 'name'],
                'unique_together': {('site', 'name')},
            },
        ),
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text="Optional label, e.g. 'Production token — added Jan 2025'", max_length=100)),
                ('encrypted_token', models.TextField(help_text='Fernet-encrypted REDCap API token — never stored in plaintext')),
                ('is_active', models.BooleanField(default=True, help_text='Only one token per project should be active at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tokens', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='The project this token authenticates against', on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='projects.siteproject')),
            ],
            options={
                'verbose_name': 'API Token',
                'verbose_name_plural': 'API Tokens',
                'db_table': 'projects_api_token',
                'ordering': ['-created_at'],
            },
        ),
    ]
