# Generated by Django 6.0.3 on 2026-05-22 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('registry', '0002_alter_centralregistry_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteproject',
            name='central_project_id',
            field=models.PositiveIntegerField(blank=True, help_text='REDCap project ID on the central registry side — used to verify the correct target project before syncing', null=True),
        ),
        migrations.AddField(
            model_name='siteproject',
            name='central_registry',
            field=models.ForeignKey(blank=True, help_text='The central registry this project syncs into', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_site_projects', to='registry.centralregistry'),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='label',
            field=models.CharField(blank=True, help_text="Optional label, e.g. 'Production token – added Jan 2025'", max_length=100),
        ),
        migrations.AlterField(
            model_name='siteproject',
            name='name',
            field=models.CharField(help_text="Descriptive name, e.g. 'Nairobi – Enrollment Form'", max_length=255),
        ),
    ]
