# Generated by Django 6.0.3 on 2026-05-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_siteproject_central_project_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitoken',
            name='encrypted_token',
            field=models.TextField(help_text='Fernet-encrypted REDCap API token – never stored in plaintext'),
        ),
        migrations.AlterField(
            model_name='siteproject',
            name='central_project_id',
            field=models.PositiveIntegerField(blank=True, help_text='REDCap project ID on the central registry side – used to verify the correct target project before syncing', null=True),
        ),
        migrations.AlterField(
            model_name='siteproject',
            name='name',
            field=models.CharField(help_text="Descriptive name, e.g. 'Nairobi – Neonatal' or 'Kisumu – Maternal'", max_length=255),
        ),
        migrations.AlterField(
            model_name='siteproject',
            name='project_id',
            field=models.PositiveIntegerField(blank=True, help_text='REDCap internal project ID – fetched automatically on token validation', null=True),
        ),
    ]
