# Generated by Django 6.0.3 on 2026-05-23 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_apitoken_encrypted_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apitoken',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='apitoken',
            name='encrypted_token',
        ),
        migrations.AddField(
            model_name='apitoken',
            name='token',
            field=models.TextField(blank=True, default='', help_text='Fernet-encrypted REDCap API token'),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='label',
            field=models.CharField(blank=True, help_text="Optional note, e.g. 'Rotated Jan 2025'", max_length=100),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to='projects.siteproject'),
        ),
        migrations.AlterField(
            model_name='site',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='siteproject',
            name='central_project_id',
            field=models.PositiveIntegerField(blank=True, help_text='REDCap project ID on the central registry — verified before syncing', null=True),
        ),
        migrations.AlterField(
            model_name='siteproject',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='siteproject',
            name='project_id',
            field=models.PositiveIntegerField(blank=True, help_text='REDCap internal project ID — fetched automatically on token validation', null=True),
        ),
        migrations.AlterField(
            model_name='siteproject',
            name='record_id_prefix',
            field=models.CharField(blank=True, help_text="Prefix added to record IDs before pushing, e.g. 'NBI-'", max_length=20),
        ),
        migrations.AlterField(
            model_name='siteproject',
            name='redcap_url',
            field=models.URLField(help_text='Full REDCap API URL, e.g. https://redcap.site.ac.ke/api/', max_length=500),
        ),
        migrations.AlterField(
            model_name='siteproject',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.site'),
        ),
        migrations.AlterField(
            model_name='siteproject',
            name='sync_fields',
            field=models.TextField(blank=True, help_text='JSON array of field names to sync. Leave blank for all.'),
        ),
        migrations.AlterField(
            model_name='siteproject',
            name='sync_forms',
            field=models.TextField(blank=True, help_text='JSON array of REDCap form names to sync. Leave blank for all.'),
        ),
    ]
