# Generated by Django 6.0.3 on 2026-04-03 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('full', 'Full Sync'), ('partial', 'Partial (Date Range)')], default='full', max_length=10)),
                ('date_from', models.DateField(blank=True, help_text='Inclusive start date (only for partial sync)', null=True)),
                ('date_to', models.DateField(blank=True, help_text='Inclusive end date (only for partial sync)', null=True)),
                ('forms_snapshot', models.TextField(blank=True, help_text='Comma-separated forms used for this job')),
                ('fields_snapshot', models.TextField(blank=True, help_text='Comma-separated fields used for this job')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('records_pulled', models.PositiveIntegerField(default=0)),
                ('records_pushed', models.PositiveIntegerField(default=0)),
                ('duration_secs', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registry', models.ForeignKey(help_text='The target registry receiving the data', on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='registry.centralregistry')),
                ('site_project', models.ForeignKey(help_text='The source project being synced', on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='projects.siteproject')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_syncs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sync Job',
                'verbose_name_plural': 'Sync Jobs',
                'db_table': 'sync_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('detail', models.JSONField(blank=True, help_text='Optional structured data — e.g. R service response, error traceback', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='sync.syncjob')),
            ],
            options={
                'verbose_name': 'Sync Log',
                'verbose_name_plural': 'Sync Logs',
                'db_table': 'sync_log',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='syncjob',
            index=models.Index(fields=['status'], name='idx_syncjob_status'),
        ),
        migrations.AddIndex(
            model_name='syncjob',
            index=models.Index(fields=['site_project', 'status'], name='idx_syncjob_project_status'),
        ),
        migrations.AddIndex(
            model_name='syncjob',
            index=models.Index(fields=['site_project', 'created_at'], name='idx_syncjob_project_date'),
        ),
        migrations.AddIndex(
            model_name='syncjob',
            index=models.Index(fields=['created_at'], name='idx_syncjob_created'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['job', 'level'], name='idx_synclog_job_level'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['job', 'timestamp'], name='idx_synclog_job_time'),
        ),
    ]
