# Generated by Django 6.0.3 on 2026-05-22 06:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_siteproject_central_project_id_and_more'),
        ('registry', '0002_alter_centralregistry_name_and_more'),
        ('sync', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='syncjob',
            name='records_skipped',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='syncjob',
            index=models.Index(fields=['registry', 'status'], name='idx_syncjob_registry_status'),
        ),
    ]
