# Generated by Django 6.0.3 on 2026-05-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_syncjob_records_skipped_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synclog',
            name='detail',
            field=models.JSONField(blank=True, help_text='Optional structured data -- e.g. R service response, error traceback', null=True),
        ),
    ]
