# Generated by Django 6.0.3 on 2026-05-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_alter_synclog_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncjob',
            name='celery_task_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='detail',
            field=models.JSONField(blank=True, help_text='Optional structured data — e.g. R service response, error traceback', null=True),
        ),
    ]
