# Generated by Django 6.0.3 on 2026-04-02 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Descriptive name, e.g. 'National TB Registry — Production'", max_length=255)),
                ('description', models.TextField(blank=True)),
                ('redcap_url', models.URLField(help_text='Central registry REDCap API URL', max_length=500)),
                ('project_id', models.PositiveIntegerField(blank=True, help_text='REDCap internal project ID — fetched on token validation', null=True)),
                ('encrypted_token', models.TextField(help_text='Fernet-encrypted registry API token')),
                ('is_active', models.BooleanField(default=True, help_text='Only one registry should be active at a time')),
                ('overwrite_with_blanks', models.BooleanField(default=False, help_text='If True, blank values from source will overwrite existing data in registry. Keep False unless intentional.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_registries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Central Registry',
                'verbose_name_plural': 'Central Registries',
                'db_table': 'registry_central_registry',
                'ordering': ['-created_at'],
            },
        ),
    ]
