# Generated by Django 6.0.3 on 2026-05-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralregistry',
            name='name',
            field=models.CharField(help_text="Descriptive name, e.g. 'National TB Registry – Production'", max_length=255),
        ),
        migrations.AlterField(
            model_name='centralregistry',
            name='overwrite_with_blanks',
            field=models.BooleanField(default=False, help_text='If True, blank values from source will overwrite existing data in the registry. Keep False unless intentional.'),
        ),
        migrations.AlterField(
            model_name='centralregistry',
            name='project_id',
            field=models.PositiveIntegerField(blank=True, help_text='REDCap internal project ID – fetched on token validation', null=True),
        ),
    ]
