# Generated by Django 6.0.3 on 2026-05-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_alter_centralregistry_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centralregistry',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='centralregistry',
            name='name',
            field=models.CharField(help_text="Descriptive name, e.g. 'National TB Registry — Production'", max_length=255),
        ),
        migrations.AlterField(
            model_name='centralregistry',
            name='project_id',
            field=models.PositiveIntegerField(blank=True, help_text='REDCap internal project ID — fetched on token validation', null=True),
        ),
    ]
