# Generated by Django 6.0.3 on 2026-05-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_remove_centralregistry_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralregistry',
            name='name',
            field=models.CharField(help_text="Descriptive name identifying the organisation, clinical area, and environment. e.g. 'KWTRP Neonatal Registry - Production' or 'KWTRP Neonatal Registry - Staging'", max_length=255),
        ),
        migrations.AlterField(
            model_name='centralregistry',
            name='overwrite_with_blanks',
            field=models.BooleanField(default=False, help_text='If True, blank values from the source will overwrite existing data in the registry. Keep False unless intentional.'),
        ),
        migrations.AlterField(
            model_name='centralregistry',
            name='project_id',
            field=models.PositiveIntegerField(blank=True, help_text='REDCap internal project ID -- fetched on token validation', null=True),
        ),
    ]
