# Generated by Django 6.0.3 on 2026-05-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_alter_centralregistry_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralregistry',
            name='encrypted_token',
            field=models.TextField(blank=True, default='', help_text='Fernet-encrypted registry API token'),
        ),
    ]
